version=0.1

[default.global.parameters]
template = "templates/api.yaml"
base_dir = "."
build_dir = "out"

[default.deploy.parameters]
template = "out/template.yaml"
capabilities = "CAPABILITY_IAM"
no_confirm_changeset = true
fail_on_empty_changeset = false
tags = "Application=\"energy\""

[default.build.parameters]
no_beta_features = true
use_container = true
s3_prefix = "energy"
