---
name: deploy-api
on:
  workflow_run:
    workflows: [checks]
    types: [completed]
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install pipenv
      - run: pipenv requirements > requirements.txt
        working-directory: app/energy_tariffs
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: sam build
        run: >2
          sam build
          --config-file samconfig.toml
      - name: sam package
        run: >2
          sam deploy
          --config-file samconfig.toml
          --s3-bucket ${{ vars.ARTIFACTS_BUCKET }}
          --stack-name ${{ vars.STACK_NAME }}
          --parameter-overrides
          DomainName=energy.berghmans.it
